### ISSUE TITLE
cannot create ether pad for certain sessions

### ISSUE THREAD

**Issue by tommykoch** [comlounge/camper#116]
noticed during pythoncamp at https://www.barcamptools.eu/pycamp201604
for certain sessions no ether pad was generated but a error message displayed instead:
"no valid padname" 

probably the session name (or slug) lead to this conflict
renaming the sessions in admin mode did help to resolve this as a quick workaround

session names that lead to this conflict are

INDUSTRIE 4.0 - INDUSTRIE IN DIE CLOUD / INNOVATIONSTAG WUPPERTAL
UNITY3D UND EINFÜHRUNG IN UNITY MIT PYTHON - 10
SICHERE INTEGRATION FÜR INTERNET DER DINGE - 8 
DIDAKTIK & TOOLS - WIE MAN PYTHON LEHRT - 10 
DISKUSSION - VERTRAUT IHR EUREN DEPENDENCIES - 8 
CROSS-PLATFORM APPS MIT PYTHON DISKUSSION - 10 
DARTBOARD MIT ARDUINO, RASPI UND LDAP - 10 
TUTORIAL ZU REST-INTERFACES MIT PYTHON 
DATA-DRIVEN SERVICES - PRODUKTE ERWEITERN -5

**Comment by mrtopf** [comment]
Additionally: etherpad has a 50 character limit, this needs to be truncated.

**Comment by mrtopf** [comment]
This is now fixed by creating a sha1 hash of the padname if it's longer than 50 chars.
