### ISSUE TITLE
amount of admins of a Barcamp

### ISSUE THREAD

**Issue by ReimarBauer** [comlounge/camper#149]
Hi 

is there an amount of admins I can add as owner. Currently I see 4 in the list but have invited more.
We have increased our organisational team. Usually 4 may be enough but in a transition process of organisational tasks I would prefer to give also newcomers the possibility to have full access.

https://barcamptools.eu/pycamp201704/permissions

**Comment by mrtopf** [comment]
I don't think I've implemented a limit. You need to make sure though the email address you enter is really the same as the one they registered with. I will have a look at it though.

**Comment by mrtopf** [comment]
I see 6 in the list. Is somebody missing? This shouldn't be cached so no idea what eventually might have happened there.

**Comment by mrtopf** [comment]
As I still see 5 and saw 6 back then I will close this as it seems not to be an issue. Otherwise please reopen.
