### ISSUE TITLE
Probleme im Zeitraster

### ISSUE THREAD

**Issue by tommykoch** [comlounge/camper#157]
Im Rahmen des PythonCamp - https://barcamptools.eu/pycamp201704 - wurden von Besuchern Probleme / Feedback berichtet: es gibt Probleme im Zeitraster mit den scrollbars:

-------- Weitergeleitete Nachricht --------
Betreff: Camper Software - Tabelle scrollen
Datum: Sat, 8 Apr 2017 11:00:24 +0200
Von: XXX
An: XXX

Hallo XXX,

der Scroll-Balken ist nicht immer sichtbar.
Die Pfeil-Tasten gehen aber gut nachdem man in die Tabelle geklickt hat.
Das sollte irgendwo gilt sichtbar an der Tabelle stehen.

Viele Grüße
XXX

**Comment by mrtopf** [comment]
Welcher Browser/OS denn? Oder mobil?

**Comment by tommykoch** [comment]
Hat Mike auf dem Mac gehabt. Vermutlich Safari. Ich hab ihm über die Schulter geschaut und kann das bestätigen ,-9

Phänomen: Das Zeitraster hat zunächst keine scrollbars - dann (click?) schon. Ist das ein IFrame? Evtl auch browser issue…

LG
Thomas

**Comment by mrtopf** [comment]
Das ist mit Version 2.3 jetzt behoben (auch schon live)

Es gibt jetzt keinen Scrollbalken, sondern ich habe die Ansicht einfach volle Breite gemacht. In der mobilen Ansicht sollte es jetzt auch richtig responsive sein.
