### ISSUE TITLE
Sponsorenbanner vor content (mobile Ansicht)

### ISSUE THREAD

**Issue by tommykoch** [comlounge/camper#158]
Im Rahmen des PythonCamp - [https://barcamptools.eu/pycamp201704]( https://barcamptools.eu/pycamp201704) - wurden von Besuchern Probleme / Feedback berichtet: auf mobilen Endgeräten (zB iPhone) erscheint immer zuerst die rechte Seite mit den Sponsorenbannern und man muss sehr weit scrollen, um zum content zu gelangen.

**Comment by mrtopf** [comment]
Das habe ich mal umgeschoben, damit der Registrieren-Button im Code vor dem Content erscheint, damit Screenreader den schneller sehen. Da denke ich mir aber noch eine andere Lösung aus.

**Comment by SpotlightKid** [comment]
Vor allem war das störend, weil man zum Zeitplan auf der Einstiegsseite des Barcamp ("Gerade läuft") soweit runter scrollen muss.

**Comment by mrtopf** [comment]
Das ist mit Version 2.3 jetzt behoben (auch schon live)
