### ISSUE TITLE
Sponsor logos not displayed in FF (OS X)

### ISSUE THREAD

**Issue by SpotlightKid** [comlounge/camper#166]
One of our sponsors for the PythonCamp reported that the sponsor logos on the right are not displayed for him in Firefox 57.0.4 on OS X on the pages of http://pythoncamp.de.

![pythoncamp_firefox_57 0 4_macosx](https://user-images.githubusercontent.com/5719151/35484949-58f017ea-0458-11e8-88ff-aa796ffec4ec.png)

Some quick investigation showed that there is an HTML syntax error in an UL section preceeding the DIV with the sponsor logo list. maybe this is causing the images not to display.

![barcamp_site_syntax_error](https://user-images.githubusercontent.com/5719151/35484959-8e8a79f4-0458-11e8-9a24-8b7af5bb0f26.png)

The logos do display on my version of FF (57.0.4, Manjaro Linux 64bit) and in Chrome on OS X.

**Comment by pya** [comment]
The same behavior with version 58.0 of FF on MacOS X. Chrome displays everything correctly.

**Comment by mrtopf** [comment]
Hm, works here but will test with Browserstack.

![image](https://user-images.githubusercontent.com/5818/35503449-734326f4-04e0-11e8-97ab-db2e10fb6ac6.png)

**Comment by mrtopf** [comment]
so I checked FF 57/58 on win and mac but all show the logos.

I added the missing `</ul>` though.

**Comment by pya** [comment]
It is the add blocker. Even though it claims not to block anything.

![abp_on](https://user-images.githubusercontent.com/952554/35505734-5552f6cc-04e7-11e8-8410-e1ac92cad19b.png)
![abp_off](https://user-images.githubusercontent.com/952554/35505737-589c4216-04e7-11e8-9b12-312bd6e32ed0.png)

**Comment by SpotlightKid** [comment]
Do the the logos of the two sponsors on the "Sponsoren" page, in the content area, display for you?

If yes, we could consider adding the logos to the content area on the front page, so that they display prominently even if the ones in the sidebar do not.

**Comment by pya** [comment]
Yes, I can see them on the "Sponsoren" page with ABP on.

**Comment by mrtopf** [comment]
ok, good to know about the blocker. I guess it's doing it's job. So while you are discussing alternatives I assume the bug for me is "fixed" (invalid might be the label for it)? 

(but feel free to finish the discussion here)

**Comment by SpotlightKid** [comment]
I suggest Mike and us (PythonCamp) resolve this via personal email.
