### ISSUE TITLE
upload logo problem

### ISSUE THREAD

**Issue by ReimarBauer** [comlounge/camper#167]
I have a png file of a sponsor which becomes not dispayed on upload 
used google-chrome
![manning-medienpartner](https://user-images.githubusercontent.com/278728/35488770-fad12f06-048d-11e8-8182-08cb672f6ee9.png)
Anything wrong with that?

**Comment by ReimarBauer** [comment]
It looks like the src conversion is not available
      <div class="sponsor clearfix">
            <a title="MANNING" href="https://www.manning.com/"><img alt="MANNING" width="220" src="/assets/"></a>
        </div>

**Comment by mrtopf** [comment]
it looks like something breaks when uploading it and thus no file is generated. On dev it works though which is strange. I will try rebuilding/updating Pillow maybe. 
(but then again it's also working on the beta on the same server with the same pillow version)

**Comment by mrtopf** [comment]
it seems to be a problem with a recent change in the nginx config. I will try to work around that now.

**Comment by mrtopf** [comment]
upload should be working again.
