### ISSUE TITLE
incomplete barcamp 

### ISSUE THREAD

**Issue by ReimarBauer** [comlounge/camper#168]
We don't have a payed barcamp but still only 88% completion

can we disable the "Rechtliches"

![bildschirmfoto von 2018-01-29 20-34-12](https://user-images.githubusercontent.com/278728/35530281-e8b74d2c-0533-11e8-8ba2-18ab15d716bb.png)

**Comment by mrtopf** [comment]
with the new version the imprint is required even for free barcamps. If you add it via the base information edit screen (not in legal), this should go away. 

I maybe should make this clearer or also add it to the legal section.

**Comment by mrtopf** [comment]
on the legal edit screen only the imprint is now required when organizing a free barcamp. So once you fill that in the progress should be 100%.
