### ISSUE TITLE
rendering issue enabling feature of participate

### ISSUE THREAD

**Issue by ReimarBauer** [comlounge/camper#186]
![bildschirmfoto von 2019-01-24 20-53-23](https://user-images.githubusercontent.com/278728/51704854-66f3c100-201a-11e9-989f-25922b82837c.png)

It is difficult to see where to click in that form. google chrome used for this.

**Comment by mrtopf** [comment]
Interesting, I did not have that on mac chrome.. I will investigate :-)

**Comment by deeplook** [comment]
I don't see any such setting at all, and don't appear on https://barcamptools.eu/pycamp201904/events, although I was there... ;)
