### ISSUE TITLE
Etherpad on Tabbed page Planung broken

### ISSUE THREAD

**Issue by acsr** [comlounge/camper#234]
Related to barcamptools.eu 
The default etherpad under the example url seems currently not functional. Maybe I missed a setting, but went through already deeply.

Example:
https://barcamps.eu/pycampcologne2022/planning

Status:
**PLANUNGS-PAD**
Das Planungs-Pad ist NICHT öffentlich (rot warnend hinterlegt)

Content:
**barcamps.eu ist kurzzeitig nicht erreichbar!**
Bitte versuche es später noch einmal!

— Dein Barcamptools-Team

**Comment by mrtopf** [comment]
Sorry, service went down but is available again.
